// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcN7t3IXL6qILpyifsnSfRAcJWKehsZDw',
    appId: '1:1060232368338:web:5c8182fc90d10726781d0b',
    messagingSenderId: '1060232368338',
    projectId: 'indianguru-36b26',
    authDomain: 'indianguru-36b26.firebaseapp.com',
    storageBucket: 'indianguru-36b26.firebasestorage.app',
    measurementId: 'G-L7VMQNDRKT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvKS_KciQh_GXH_efbmrGAew9UeNhnYcM',
    appId: '1:1060232368338:android:f1fe2d56b75ab5b9781d0b',
    messagingSenderId: '1060232368338',
    projectId: 'indianguru-36b26',
    storageBucket: 'indianguru-36b26.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAevFklvNl6mPU7LaGa8ksqfLZVxPqdXSE',
    appId: '1:1060232368338:ios:736d709eb34903dd781d0b',
    messagingSenderId: '1060232368338',
    projectId: 'indianguru-36b26',
    storageBucket: 'indianguru-36b26.firebasestorage.app',
    iosBundleId: 'com.example.indianGuru',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAevFklvNl6mPU7LaGa8ksqfLZVxPqdXSE',
    appId: '1:1060232368338:ios:736d709eb34903dd781d0b',
    messagingSenderId: '1060232368338',
    projectId: 'indianguru-36b26',
    storageBucket: 'indianguru-36b26.firebasestorage.app',
    iosBundleId: 'com.example.indianGuru',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBcN7t3IXL6qILpyifsnSfRAcJWKehsZDw',
    appId: '1:1060232368338:web:21446b31a76d15b2781d0b',
    messagingSenderId: '1060232368338',
    projectId: 'indianguru-36b26',
    authDomain: 'indianguru-36b26.firebaseapp.com',
    storageBucket: 'indianguru-36b26.firebasestorage.app',
    measurementId: 'G-GW06PL0LLQ',
  );
}
